on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploying
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Getting the latest code
        uses: actions/checkout@v3

      # Optional: Install NPM Packages if using JavaScript
      - name: Install NPM Packages
        run: npm install

      # Sync files to server
      - name: 📂 Sync
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.nexoratech.co.ke
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /
